include: package:flutter_lints/flutter.yaml

linter:
  rules:
    use_function_type_syntax_for_parameters: false
    prefer_single_quotes: true
    prefer_relative_imports: true
    unawaited_futures: true
    prefer_typing_uninitialized_variables: false
    prefer_function_declarations_over_variables: false

analyzer:
  exclude:
    - '**.g.dart'
    - '**.freezed.dart'
    - '**.mocks.dart'
